spring.application.name=gradiance
server.port=8085


logging.level.org.springframework.jdbc=DEBUG

spring.mvc.static-path-pattern=/templates/**
spring.datasource.url= jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=12345
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update